language: ruby
matrix:
  include:
    - rvm: 1.8.7
      env: PUPPET_VERSION=3.8.2
      gemfile: Gemfile
  allow_failures:
    - rvm: 2.2.0
      env: PUPPET_VERSION=3.8.2
script:
  - "bundle exec rake validate"
  - "bundle exec rake lint"
  - "bundle exec rake spec"
