language: ruby
matrix:
  include:
    - rvm: 1.8.7
      env: PUPPET_VERSION=2.7.17
      gemfile: Gemfile
    - rvm: 1.8.7
      env: PUPPET_VERSION=3.7.4
      gemfile: Gemfile
    - rvm: 2.2.0
      env: PUPPET_VERSION=4.2.2
      gemfile: Gemfile
  allow_failures:
    - rvm: 2.2.0
      env: PUPPET_VERSION=3.7.4
script:
  - "bundle exec rake validate"
  - "bundle exec rake lint"
  - "bundle exec rake spec"
notifications:
  email:
    on_failure: always
sudo: false
